name: sentry-release

on:
  push:
    branches:
      - '**'

jobs:
  createSentryRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create a Sentry.io release
        uses: getsentry/action-release@v1.4.1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: freelawproject
          SENTRY_PROJECT: courtlistener
        with:
          version: ${{ github.sha }}
          environment: prod
